### PR TITLE
Update README to cover purpose and process of repo

### PR DESCRIPTION
**Pull request by evilstreak**
This repo contains HTML templates which don't get deployed onto the GOV.UK infrastructure like most our repos. Try to be more explicit about what this code is for and how it's used and updated.

This could probably do with a review from @futurefabric to confirm its accuracy and fill in the blanks.

### CODE REVIEW

**Comment by futurefabric** [comment]
@evilstreak Hello! I can look at this today. Shall I update the readme on this branch and we can go from there?

**Comment by futurefabric** [comment]
@evilstreak Updated readme and tidied up files. Thoughts?

**Comment by evilstreak** [comment]
Great, thanks!

What is `email_alert.html` actually used for now? It is it just static example of what a non-DSU email alert looks like? Ie, it's the code that exists in Specialist Publisher?

I'll give this another pass and try to fish out some of the other files we reference (eg the Whitehall ones), or at least add a list of things that ought to be included in this repo but aren't

**Comment by futurefabric** [comment]
Sorry, good point. Yes, `email_alert.html` _is_ a static example of the drug and device alerts email. As it already exists in Specialist Publisher, feel free to can it. I just held onto it as it was the source file I worked from before handing over the code to Andy to integrate into Specialist Publisher.

**Comment by evilstreak** [comment]
This is ready to review and merge now

**Pull request merged**
